### ISSUE TITLE
Titan V support

### ISSUE THREAD

**Issue by luca-bondi** [Splo0sh/netdata_nv_plugin#10]
In order to support for Titan V the following line:

https://github.com/coraxx/netdata_nv_plugin/blob/a99824a6efea2d34a75065acd566addc87c3152a/nv.chart.py#L259

as to be modified into:
brands = ['Unknown', 'Quadro', 'Tesla', 'NVS', 'Grid', 'GeForce', 'Titan']

**Comment by coraxx** [comment]
Thanks for the fix :+1:
