### ISSUE TITLE
GPU mem usage graph type

### ISSUE THREAD

**Issue by tijmenvn** [Splo0sh/netdata_nv_plugin#12]
The current memory usage graph shows only two lines with "free" and "used" data. Can this be made into a similar graph as RAM usage, as now it's still not very clear at first sight to see how much memory you got left:
![Capture](https://user-images.githubusercontent.com/9320891/55004981-86d44080-4fdb-11e9-9a90-24ae37ee2611.PNG)
Picture above how RAM usage is done, and how the prefered way to plot VRAM usage should look like

**Comment by coraxx** [comment]
Hi, you could try to set the graph type https://github.com/coraxx/netdata_nv_plugin/blob/ccf9651f67beae75268b95006fc47e4aaf7d08ba/nv.chart.py#L73 from `line` to `stacked`

https://github.com/netdata/netdata/issues/2439#issuecomment-314085541

As soon as I have a system to test this on, I can make a permament change here. Or if you can test it and can get back to me if it is working, that would be great as well 🥇

**Comment by tijmenvn** [comment]
Hey, changing it to stacked indeed worked. However. With the way stacked works, You'd still need to swap the order for "free" and "used". Because now you get this:
![Capture](https://user-images.githubusercontent.com/9320891/55062898-1d097480-5077-11e9-9ffe-5d85b9ceee36.PNG)
So if there is a way too swap them. I'd think we're set.

EDIT:
I swapped the following lines:
https://github.com/coraxx/netdata_nv_plugin/blob/ccf9651f67beae75268b95006fc47e4aaf7d08ba/nv.chart.py#L171-L172
to see if that changed the priority, and it did :). Chart looks like this now:
![Capture](https://user-images.githubusercontent.com/9320891/55063266-ed0ea100-5077-11e9-82c2-c52a4daeda20.PNG)

**Comment by coraxx** [comment]
Perfect, looks good :)
Do you want to make a pull request? Otherwise I will apply your changes asap.
