### ISSUE TITLE
dependency problems

### ISSUE THREAD

**Issue by vaheminasyan** [Splo0sh/netdata_nv_plugin#3]
Hi.

When i try to run the 'nv.chart.py' , it throws such an error.

    Traceback (most recent call last):
    File "nv.chart.py", line 50, in <module>
    from base import SimpleService
    ImportError: No module named base

and if I try to install base, it show's following
    
    Traceback (most recent call last):
    File "nv.chart.py", line 50, in <module>
    from base import SimpleService
    ImportError: cannot import name SimpleService
    
How could it be fixed.

**Comment by coraxx** [comment]
Are you running it manually? You have to install it to the netdata pluginfolder. Check [https://github.com/coraxx/netdata_nv_plugin](https://github.com/coraxx/netdata_nv_plugin) on how to install it.

The ```base``` that python cannot find, are base imports from [netdata](https://github.com/firehol/netdata/blob/master/python.d/python_modules/base.py) itself.

**Comment by vaheminasyan** [comment]
Thank you.
In real the problem was that I was trying to install files in  `/usr/libexec/netdata `
while my netdata libs are installed in` /usr/lib/x86_64-linux-gnu/netdata`
