### ISSUE TITLE
Multiple GPUs support

### ISSUE THREAD

**Issue by yarons** [Splo0sh/netdata_nv_plugin#4]
Currently the graph lines shows either the average or accumulation (I can't really determine which one of them is applied).

Is there a way to chart individual graph lines for each and every GPU?

Depiction of the current situation:
![image](https://user-images.githubusercontent.com/406826/37763743-8d5c55ae-2dc8-11e8-9c64-134512de75bf.png)

**Comment by coraxx** [comment]
Hmm, it should look like this #2 if more gpus are active. Here it seems load is only read for the first GPU ([0]). Do the other graphs show you information for both GPUs ([0] and [1])?

**Comment by yarons** [comment]
They all show a single graph for [0], these are different PCI Express cards connected to different CPUs, the GPUs are completely identical.

**Comment by coraxx** [comment]
Could you post the output of the `nvidia-smi` command line tool?

**Comment by yarons** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:03:00.0  On |                  Off |
| 28%   63C    P5    27W / 250W |  23268MiB / 24446MiB |     35%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro P6000        Off  | 00000000:A1:00.0 Off |                  Off |
| 26%   49C    P8    19W / 250W |  23239MiB / 24449MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      5331      G   /usr/lib/xorg/Xorg                           373MiB |
|    0      7154      G   /usr/bin/compiz                              186MiB |
|    0     24956      G   ...quest-channel-token=7324468127765022943    67MiB |
|    0     30002      C   /usr/local/bin/python3.6                   22601MiB |
|    0     55160      G   /opt/teamviewer/tv_bin/TeamViewer             28MiB |
|    1     30002      C   /usr/local/bin/python3.6                   23227MiB |
+-----------------------------------------------------------------------------+
```

**Comment by coraxx** [comment]
The only thing I can think of is that all values for the second card are 0, because then if I remember correctly, NetData is not showing the graph for it. But then the nvidia-smi's reporting is incorrect?! It's hard for me to check without such a configuration at hand (two separate CPUs with separate PCI lanes and two GPUs). I will ask a friend who I think has a similar setup as yours, to let me tinker with it :)

**Comment by coraxx** [comment]
I'm sorry, I was not able to replicate the problem. If at some point I have the opportunity to test a similar setup, I will reopen it. If you have any new information you are welcome to share it.
