### ISSUE TITLE
Plugin doesn't load on Ubuntu 18.04/Netdata v1.9.0

### ISSUE THREAD

**Issue by thehomerepot** [Splo0sh/netdata_nv_plugin#6]
I installed this plugin on Ubuntu 18.04 with Netdata v1.9.0. I had to use the following file location modifications.

cd /tmp/
git clone https://github.com/Splo0sh/netdata_nv_plugin --depth 1
cp netdata_nv_plugin/nv.chart.py /usr/lib/x86_64-linux-gnu/netdata/python.d/
cp netdata_nv_plugin/python_modules/pynvml.py /usr/lib/x86_64-linux-gnu/netdata/python.d/python_modules/
cp netdata_nv_plugin/nv.conf /etc/netdata/python.d/
systemctl restart netdata

Despite this, no GPU data is loaded into netdata. I don't see any log information about nv.conf at all. Any way to troubleshoot why it's not loading?

**Comment by thehomerepot** [comment]
Nevermind, looks like it's an issue with the v1.9.0 netdata deb package.
https://github.com/netdata/netdata/pull/3949

**Comment by Neldogz** [comment]
Confirmed this plugin does not work with Ubuntu 18.04 after following the installation procedures. The nvidia graph does not appear after restarting both netdata and reconnecting to netdata via the browser:

Install:

```
usr1@comp:/tmp$ git clone https://github.com/Splo0sh/netdata_nv_plugin --depth 1
Cloning into 'netdata_nv_plugin'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
```

```
usr1@comp:/tmp$ sudo cp netdata_nv_plugin/nv.chart.py /usr/lib/x86_64-linux-gnu/netdata/python.d/
usr1@comp:/tmp$ sudo cp netdata_nv_plugin/python_modules/pynvml.py /usr/lib/x86_64-linux-gnu/netdata/python.d/python_modules/
usr1@comp:/tmp$ sudo cp netdata_nv_plugin/nv.conf /etc/netdata/python.d/
```

sudo systemctl restart netdata

Information:

```
usr1@comp:/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

user1@comp:/tmp$ python -V
Python 2.7.15+

user1@comp:/tmp$ python3 -V
Python 3.6.8

user1@comp:/tmp$ netdata -V
netdata 1.9.0
```
(Installed from the Ubuntu 18.04 repositories)
