### ISSUE TITLE
No module named bases.FrameworkServices.SimpleService

### ISSUE THREAD

**Issue by TheFlipside** [Splo0sh/netdata_nv_plugin#8]
netdata installation on debian 9.5

followed the installation steps though there is no /usr/libexec/ on debian, the needed path is /usr/lib/x86_64-linux-gnu/netdata/python.d/python_modules/
the readme lacks in that regard

but now when restarting the netdata daemon this error occurs:
python.d ERROR: Problem loading nv No module named bases.FrameworkServices.SimpleService

**Comment by coraxx** [comment]
Have you installed netdata via the netdata installer script or via a package manager? #6
Also, do you have the latest version installed? netdata/netdata@7f9afed

I'm also on debian but version 7 and for me it is /usr/libexec/. I will update the readme, thanks for the heads up regarding the path.

**Comment by TheFlipside** [comment]
i had to enable the stretch-backports repository and was then able to install via package manager 
_sudo apt install netdata_
netdata on version 1.6.0 that way

looking at this https://github.com/netdata/netdata/commit/7f9afed told me what to do, i replaced in **/usr/lib/x86_64-linux-gnu/netdata/python.d/nv.chart.py** the line `from bases.FrameworkServices.SimpleService import SimpleService` with `from base import SimpleService` and restarted netdata
its working now
quite the backflip workaround for debian 9.5
